package api

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os" // Added for robust path construction
	"strings"
	"sync"
)

var loadEnvOnce sync.Once
var DotEnvPath = ".env" // Exported for testability

// GetGeminiAPIURL is a variable that holds a function to get the Gemini API URL. This allows overriding for testing.
var GetGeminiAPIURL = func(apiKey string) string {
	return "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" + apiKey
}

// ResetLoadEnvOnce is a helper function for testing to reset the sync.Once for loadEnvFromFile.
func ResetLoadEnvOnce() {
	loadEnvOnce = sync.Once{}
}

func loadEnvFromFile() error {
	envFilePath := DotEnvPath // Use the configurable DotEnvPath
	file, err := os.Open(envFilePath)
	if err != nil {
		if os.IsNotExist(err) {
			fmt.Printf("Warning: .env file not found at %s. Relying on pre-set environment variables.\n", envFilePath)
			return nil
		}
		return fmt.Errorf("error opening .env file at %s: %w", envFilePath, err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			if len(value) > 1 && ((strings.HasPrefix(value, "\\\"") && strings.HasSuffix(value, "\\\"")) || (strings.HasPrefix(value, "'") && strings.HasSuffix(value, "'"))) {
				value = value[1 : len(value)-1]
			}
			os.Setenv(key, value)
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("error reading .env file: %w", err)
	}
	return nil
}

type GeminiRequestPayload struct {
	Contents []Content `json:"contents"`
}

type Content struct {
	Parts []Part `json:"parts"`
}

type Part struct {
	Text string `json:"text"`
}

// Defines the structure for the Gemini API response
type GeminiResponsePayload struct {
	Candidates     []Candidate     `json:"candidates"`
	PromptFeedback *PromptFeedback `json:"promptFeedback,omitempty"`
}

// Candidate holds the content generated by the model
type Candidate struct {
	Content       Content        `json:"content"`
	FinishReason  string         `json:"finishReason"`
	Index         int            `json:"index"`
	SafetyRatings []SafetyRating `json:"safetyRatings"`
}

// SafetyRating defines the safety rating for the generated content
type SafetyRating struct {
	Category    string `json:"category"`
	Probability string `json:"probability"`
}

// PromptFeedback contains feedback per prompt
type PromptFeedback struct {
	SafetyRatings []SafetyRating `json:"safetyRatings"`
}

// GetGeminiExplanation calls the Gemini API to get an explanation for a chess move
func GetGeminiExplanation(fen string, bestMove string) (string, error) {
	loadEnvOnce.Do(func() {
		if err := loadEnvFromFile(); err != nil {
			fmt.Printf("Error loading .env file: %v\n", err)
		}
	})

	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return "", fmt.Errorf("GEMINI_API_KEY not set. Please ensure it's in .env or your environment")
	}

	apiURL := GetGeminiAPIURL(apiKey) // Use the GetGeminiAPIURL function variable

	prompt := fmt.Sprintf("You are a chess grandmaster. Given the following chess position in FEN notation: %s, Stockfish suggests the best move is %s. Explain why this is a good move, considering tactical advantages, strategic goals, and potential opponent responses. Keep your explanation concise and suitable for a chess enthusiast.", fen, bestMove)

	payload := GeminiRequestPayload{
		Contents: []Content{
			{
				Parts: []Part{
					{Text: prompt},
				},
			},
		},
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("error marshalling Gemini request payload: %w", err)
	}

	req, err := http.NewRequest("POST", apiURL, bytes.NewBuffer(payloadBytes))
	if err != nil {
		return "", fmt.Errorf("error creating Gemini request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("error sending request to Gemini API: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gemini API request failed with status %s: %s", resp.Status, string(bodyBytes))
	}

	var geminiResp GeminiResponsePayload
	if err := json.NewDecoder(resp.Body).Decode(&geminiResp); err != nil {
		return "", fmt.Errorf("error decoding Gemini API response: %w", err)
	}

	if len(geminiResp.Candidates) > 0 && len(geminiResp.Candidates[0].Content.Parts) > 0 {
		return geminiResp.Candidates[0].Content.Parts[0].Text, nil
	}

	// Check for prompt feedback if no candidates are present or parts are empty
	if geminiResp.PromptFeedback != nil {
		for _, rating := range geminiResp.PromptFeedback.SafetyRatings {
			if rating.Probability != "NEGLIGIBLE" && rating.Probability != "LOW" {
				return "", fmt.Errorf("content blocked by Gemini API due to safety concerns: Category %s, Probability %s", rating.Category, rating.Probability)
			}
		}
	}

	return "", fmt.Errorf("no explanation found in Gemini API response or content was blocked (candidates: %d, prompt feedback: %v)", len(geminiResp.Candidates), geminiResp.PromptFeedback)
}
